from setuptools import setup, find_packages

setup(
    name="aios",
    version="0.1.0",
    description="AI Operating System",
    long_description="A comprehensive AI-powered operating system with advanced cognitive computing capabilities.",
    author="AIOS Team",
    author_email="team@aios.ai",
    url="https://github.com/aios/aios",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn==0.24.0",
        "python-jose==3.3.0",
        "passlib==1.7.4",
        "bcrypt==4.0.1",
        "python-multipart==0.0.6",
        "rich==13.6.0",
        "spacy==3.7.2",
        "transformers==4.35.2",
        "torch==2.1.1",
        "docker==6.1.3",
        "psutil==5.9.6",
        "scikit-learn==1.3.2",
        "numpy==1.26.2",
        "ray>=2.0.0",
        "pydantic>=1.8.2",
        "pandas>=1.3.0",
        "python-dotenv>=0.19.0",
        "aiofiles>=0.8.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.9",
    include_package_data=True,
    zip_safe=False,
)
